[tool.poetry]
name = "webvox"
version = "0.1.0"
description = ""
authors = ["Purav <puravparabdev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.10"
jupyter = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
