[tool.poetry]
name = "webvox-notebooks"
version = "0.1.0"
description = ""
authors = ["Purav <puravparabdev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ollama = "^0.3.3"
bs4 = "^0.0.2"
tiktoken = "^0.8.0"
requests = "^2.32.3"
unidic = "^1.1.0"
nltk = "^3.9.1"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
